新学到了environment.d一些东西
ArchLinuxStudio/ArchLinuxTutorial pull request #71
Opened 2021-11-07 12:50 UTC by chen244

也许可以用的上
用户级别的环境变量配置

2021-11-07 12:54 UTC, livrth requested changes
建议补充一下 `environment.d` arch wiki 参考链接，以及格式上把路径用单引号格式括起来，或者用代码块也可以。

2021-11-07 13:24 UTC, livrth approved these changes

2021-11-07 14:36 UTC, TakoTakoo commented
This doc is not wiki.

2021-11-07 14:38 UTC, chen244 commented
> This doc is not wiki.

就是提供了其他的配置地方而已，用户级别配置的地方

2021-12-12 14:27 UTC, ryosukeeeeee commented
Time has passed for a long time and has been replied, closed.

2021-12-12 14:27 UTC, closed without merging