添加了关于 `sudoedit` 和 `visudo` 的说明 (Fix #75)
ArchLinuxStudio/ArchLinuxTutorial pull request #80
Opened 2021-12-17 16:57 UTC by GalaxySnail

2021-12-17 16:58 UTC, livrth approved these changes

2021-12-19 01:10 UTC, ryosukeeeeee commented on docs/rookie/DE&App.md
> +```sudoers
Why change "bash" to "sudoers" here?

2021-12-19 01:11 UTC, ryosukeeeeee commented on docs/rookie/DE&App.md
> +```sudoers
Same as line 38.

2021-12-19 01:26 UTC, ryosukeeeeee requested changes
Thank you. Please see the comment line.

2021-12-19 08:22 UTC, GalaxySnail commented on docs/rookie/DE&App.md
> +```sudoers
因为这段代码显然不是 bash 语法，而是 sudoers 配置文件的语法，见手册 [sudoers(5)](https://man.archlinux.org/man/sudoers.5#SUDOERS_FILE_FORMAT)。我不确定哪些 markdown 渲染器支持对 sudoers 语法进行高亮，但是即使不能高亮，标记上 sudoers 总的来说也不会错，而且对直接阅读源码的用户来说更加友好。

（顺便一提，我觉得对于纯中文的文档而言，不论是注释、还是 commit message、还是社区讨论，应该都没有使用英语的必要吧）

2021-12-19 09:23 UTC, ryosukeeeeee commented on docs/rookie/DE&App.md
> +```sudoers
Fine.

(Because Chinese is not my first language, I am more accustomed to communicating in English.)

2021-12-19 09:23 UTC, ryosukeeeeee approved these changes

2021-12-19 09:23 UTC, merged